const express = require('express');
const familyRouter = express.Router();
const family = require('./family.controllers');
const { auth } = require('../../middlewares');
const multer = require('multer');
const upload = multer();

familyRouter.post('/create', auth, family.CreateFamily);
familyRouter.get('/home', auth, family.Home);
familyRouter.post('/upload', auth, family.Upload);
familyRouter.put('/update', auth, family.UpdateFamily);
familyRouter.post('/event/create', auth, family.CreateEvent);
familyRouter.delete('/event/delete/:id', auth, family.DeleteEvent);
familyRouter.get('/event/view/:date', auth, family.ViewEvent);
familyRouter.get('/event/notification/:date', auth, family.EventNotification);
familyRouter.post('/album/create', auth, family.AlbumCreate);
familyRouter.get('/album/view/:id', auth, family.AlbumSingleView);
familyRouter.post('/album/upload/:id', auth, family.AlbumSingleAdd);
familyRouter.get('/album/view', auth, family.AlbumView);
familyRouter.get('/tree', auth, family.Tree);
module.exports = familyRouter;
